# -*- coding: utf-8 -*-
"""coding_web.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vd2_VNHWQDfhkLaySsCjKgHVWfVa2qb7
"""

!pip install streamlit plotly pandas numpy openpyxl

!wget -qO- ipv4.icanhazip.com

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# from __future__ import annotations
# import subprocess
# import sys
# from pathlib import Path
# 
# def _running_inside_streamlit() -> bool:
#     try:
#         from streamlit.runtime.scriptrunner import get_script_run_ctx
#         return get_script_run_ctx() is not None
#     except Exception:
#         return False
# 
# if __name__ == "__main__" and not _running_inside_streamlit():
#     script = Path(__file__).resolve()
#     raise SystemExit(subprocess.call([sys.executable, "-m", "streamlit", "run", str(script)]))
# 
# import numpy as np
# import pandas as pd
# import plotly.graph_objects as go
# import streamlit as st
# 
# # ==========================================
# # 1. PARAMETER DATA REGIONAL LAMPUNG
# # ==========================================
# BASE_DIR = Path(__file__).resolve().parent
# EWS_PATH = BASE_DIR / "EWS.xlsx"
# 
# LAMPUNG_REGENCIES = ["Lampung Utara", "Tanggamus", "Tulang Bawang", "Lampung Timur", "Pringsewu", "Lampung Selatan", "Way Kanan", "Pesawaran"]
# 
# PEST_CONFIG = {
#     "Kepik Penghisap Buah (Helopeltis spp.)": {
#         "komoditas": "Kakao / Lada", "opt": "Helopeltis spp.", "tipe": "serangga",
#         "t_base": 12.5, "batas_max": 300, "satuan": "GDD",
#         "batas_1": 94.25, "batas_2": 275.5,
#         "label_1": "Fase Telur", "label_2": "Fase Nimfa", "label_3": "Imago Dewasa",
#         "deskripsi": "Hama Kepik Penghisap (Helopeltis spp.) merusak buah muda dan pucuk daun tanaman kakao/lada di Lampung, memicu bercak hitam melingkar nekrotik. Tingkat serangan parah mengakibatkan buah membusuk kering dan mengeras (buah mumi)."
#     },
#     "Kumbang Nyiur Kelapa (Oryctes rhinoceros)": {
#         "komoditas": "Kelapa Sawit / Kelapa", "opt": "Oryctes rhinoceros", "tipe": "serangga",
#         "t_base": 15.0, "batas_max": 2000, "satuan": "GDD",
#         "batas_1": 120, "batas_2": 1800,
#         "label_1": "Fase Telur", "label_2": "Larva / Uret", "label_3": "Pupa & Imago",
#         "deskripsi": "Kumbang Tanduk/Nyiur merusak pelepah muda kelapa sawit rakyat di Lampung. Membawa pola potongan daun berbentuk huruf V yang simetris saat pelepah membuka, mengancam titik tumbuh utama pohon."
#     },
#     "Penggerek Buah Kakao (Conopomorpha cramerella)": {
#         "komoditas": "Kakao", "opt": "Conopomorpha cramerella", "tipe": "serangga",
#         "t_base": 11.5, "batas_max": 260, "satuan": "GDD",
#         "batas_1": 120.9, "batas_2": 247.0,
#         "label_1": "Pupa Betina", "label_2": "Pupa Jantan", "label_3": "Imago Aktif",
#         "deskripsi": "Hama Penggerek Buah Kakao (PBK) merusak dengan cara larva masuk ke dalam daging buah dan menggerogoti biji kakao di perkebunan Lampung. Biji berisiko saling lengket, membusuk hitam, dan menurunkan kualitas mutu panen."
#     }
# }
# 
# # ==========================================
# # 2. THEME RESKIN TOTAL (SLATE & STEEL BLUE INDUSTRIAL)
# # ==========================================
# st.set_page_config(page_title="EWS OPT Lampung v2", page_icon="📊", layout="wide", initial_sidebar_state="expanded")
# 
# MODERN_CSS = """
# <style>
# @import url('https://fonts.googleapis.com/css2?family=Segoe+UI:wght@400;600;700&display=swap');
# 
# html, body, [class*="css"] {
#     font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif !important;
#     color: #334155 !important;
# }
# 
# .stApp { background-color: #f1f5f9 !important; }
# 
# /* MAIN LAYER CONTAINER */
# .block-container {
#     background-color: #ffffff !important;
#     border-radius: 8px;
#     padding: 2.5rem !important;
#     margin-top: 1rem !important;
#     max-width: 1350px;
#     box-shadow: 0 1px 3px rgba(0,0,0,0.1);
# }
# 
# /* SIDEBAR BRANDING */
# [data-testid="stSidebar"] {
#     background-color: #0f172a !important;
#     color: #ffffff !important;
# }
# [data-testid="stSidebar"] * { color: #f8fafc !important; }
# 
# /* HERO BANNER MINIMALIS */
# .brand-banner {
#     background-color: #1e3a8a; /* Biru Navy Solid */
#     padding: 25px;
#     border-radius: 6px;
#     margin-bottom: 30px;
# }
# .brand-title { color: #ffffff !important; margin: 0; font-weight: 700; font-size: 1.9rem; }
# .brand-subtitle { color: #93c5fd !important; margin: 4px 0 0 0; font-size: 0.95rem; font-weight: 400; }
# 
# /* METRIC CARDS FLAT DESIGN */
# .box-metric {
#     background: #f8fafc;
#     border-radius: 6px;
#     padding: 20px;
#     border-left: 5px solid #64748b;
#     border-top: 1px solid #e2e8f0;
#     border-right: 1px solid #e2e8f0;
#     border-bottom: 1px solid #e2e8f0;
# }
# .box-safe { border-left-color: #10b981; }
# .box-warn { border-left-color: #f59e0b; }
# .box-danger { border-left-color: #ef4444; }
# 
# .box-lbl { font-size: 0.75rem; font-weight: 700; color: #64748b !important; text-transform: uppercase; margin-bottom: 5px;}
# .box-val { font-size: 1.5rem; font-weight: 700; color: #0f172a !important; margin-bottom: 2px;}
# .box-inf { font-size: 0.85rem; color: #475569 !important;}
# 
# /* SECTION HEADERS */
# .page-header { font-size: 1.2rem; font-weight: 700; color: #1e3a8a !important; margin: 1.5rem 0 1rem 0; text-transform: uppercase; letter-spacing: 0.02em;}
# 
# /* ALERT INTERVENSI */
# .alert-card { padding: 20px; border-radius: 6px; font-size: 0.95rem; line-height: 1.6; margin-top: 15px;}
# .alert-g-safe { background-color: #f0fdf4; border: 1px solid #bbf7d0; color: #166534 !important;}
# .alert-g-warn { background-color: #fffbeb; border: 1px solid #fef08a; color: #92400e !important;}
# .alert-g-danger { background-color: #fef2f2; border: 1px solid #fecaca; color: #991b1b !important;}
# 
# div[data-testid="stDataFrame"] { border-radius: 6px; overflow: hidden; border: 1px solid #cbd5e1;}
# </style>
# """
# st.markdown(MODERN_CSS, unsafe_allow_html=True)
# 
# def draw_custom_metric(label, value, desc, status="Netral"):
#     status_class = "box-safe" if status == "Aman" else ("box-warn" if status == "Waspada" else ("box-danger" if status == "Bahaya" else ""))
#     st.markdown(f'<div class="box-metric {status_class}"><div class="box-lbl">{label}</div><div class="box-val">{value}</div><div class="box-inf">{desc}</div></div>', unsafe_allow_html=True)
# 
# # ==========================================
# # 3. ENGINE PEMROSESAN DATA
# # ==========================================
# @st.cache_data(show_spinner=False)
# def load_data():
#     weather = pd.read_excel(EWS_PATH, sheet_name="DATA CUACA")
#     weather = weather.rename(columns={"Tanggal": "date", "Kabupaten": "regency", "CH (mm)": "rain_mm", "Tmin": "tmin", "Tmax": "tmax", "RH": "rh"})
#     weather["date"] = pd.to_datetime(weather["date"], errors="coerce")
#     for col in ["rain_mm", "tmin", "tmax", "rh"]: weather[col] = pd.to_numeric(weather[col], errors="coerce")
#     weather = weather.dropna(subset=["date", "regency"])
#     weather = weather[weather["regency"].isin(LAMPUNG_REGENCIES)]
#     weather["tmean"] = (weather["tmin"] + weather["tmax"]) / 2
# 
#     enso = pd.read_excel(EWS_PATH, sheet_name="ENSO INDEX")
#     enso = enso.rename(columns={enso.columns[0]: "date", enso.columns[1]: "nino34"})
#     enso["date"] = pd.to_datetime(enso["date"], errors="coerce")
#     enso["nino34"] = pd.to_numeric(enso["nino34"], errors="coerce")
#     enso["year_month"] = enso["date"].dt.to_period("M")
# 
#     return weather, enso
# 
# def proses_prediksi(weather, enso, config, tgl_mulai, durasi_hari):
#     tgl_awal = pd.to_datetime(tgl_mulai)
#     tgl_akhir = tgl_awal + pd.Timedelta(days=durasi_hari)
# 
#     df = weather[(weather['date'] >= tgl_awal) & (weather['date'] <= tgl_akhir)].copy()
#     if df.empty: return pd.DataFrame()
# 
#     df['year_month'] = df['date'].dt.to_period('M')
#     df = df.merge(enso[['year_month', 'nino34']], on='year_month', how='left').drop(columns=['year_month'])
#     df['nino34'] = df['nino34'].fillna(0)
# 
#     hasil_harian = []
#     for reg in df['regency'].unique():
#         pdf = df[df['regency'] == reg].copy()
#         pdf['hari_ke'] = (pdf['date'] - tgl_awal).dt.days
# 
#         pdf['gdd_harian'] = np.maximum(((pdf['tmax'] + pdf['tmin']) / 2) - config['t_base'], 0)
#         pdf['cum_gdd'] = pdf['gdd_harian'].cumsum()
#         pdf['indikator'] = pdf['cum_gdd'] % config['batas_max']
#         pdf['generasi'] = (pdf['cum_gdd'] // config['batas_max']) + 1
# 
#         b1, b2 = config['batas_1'], config['batas_2']
#         pdf['status'] = np.where(pdf['indikator'] <= b1, 'Aman', np.where(pdf['indikator'] <= b2, 'Waspada', 'Bahaya'))
#         pdf['fase'] = np.where(pdf['indikator'] <= b1, config['label_1'], np.where(pdf['indikator'] <= b2, config['label_2'], config['label_3']))
# 
#         hasil_harian.append(pdf)
#     return pd.concat(hasil_harian, ignore_index=True)
# 
# # ==========================================
# # 4. TEKS INFORMASI AKADEMIK
# # ==========================================
# def get_enso_box(opt_name, rata_nino):
#     if rata_nino >= 0.5:
#         if "Oryctes" in opt_name:
#             return f"<div style='background-color:#fff1f2; border:1px solid #fecaca; padding:15px; border-radius:6px; font-size:0.95rem;'><b>🔴 Dinamika Makro: El Niño ({rata_nino:.2f})</b><br>Tanaman kelapa sawit di Lampung berpotensi mengalami cekaman kekeringan harian. Kondisi pelepah yang tertekan memicu penguapan senyawa kimia alami yang memancing serbuan hama imago Oryctes rhinoceros.</div>"
#         else:
#             return f"<div style='background-color:#f0fdf4; border:1px solid #bbf7d0; padding:15px; border-radius:6px; font-size:0.95rem;'><b>🟢 Dinamika Makro: El Niño ({rata_nino:.2f})</b><br>Kondisi kering di Lampung menurunkan tingkat kelembapan mikro. Menjadi pembatas alami yang menekan perkembangbiakan telur kepik Helopeltis dan stadium uret PBK.</div>"
#     elif rata_nino <= -0.5:
#         if "Oryctes" in opt_name:
#             return f"<div style='background-color:#f8fafc; border:1px solid #cbd5e1; padding:15px; border-radius:6px; font-size:0.95rem;'><b>🔵 Dinamika Makro: La Niña ({rata_nino:.2f})</b><br>Tingginya curah hujan harian mempercepat pembusukan limbah kayu tebangan tua di Lampung, menyediakan sarang perkembangbiakan uret tanah secara melimpah.</div>"
#         else:
#             return f"<div style='background-color:#fff1f2; border:1px solid #fecaca; padding:15px; border-radius:6px; font-size:0.95rem;'><b>🔴 Dinamika Makro: La Niña ({rata_nino:.2f})</b><br>Lingkungan perkebunan Lampung menjadi sangat basah dan lembap. Memberikan perlindungan bagi nimfa Helopeltis dan pupa PBK dari risiko dehidrasi alami. Potensi outbreak tinggi.</div>"
#     else:
#         return f"<div style='background-color:#fffbeb; border:1px solid #fef08a; padding:15px; border-radius:6px; font-size:0.95rem;'><b>🟡 Dinamika Makro: ENSO Netral ({rata_nino:.2f})</b><br>Kondisi atmosfer global dalam kisaran normal harian. Dinamika naik-turun populasi hama dikendalikan murni oleh fluktuasi cuaca lokal di tingkat kabupaten.</div>"
# 
# def get_mitigasi_box(opt_name, status, kab):
#     a_class = "alert-g-safe" if status == "Aman" else ("alert-g-warn" if status == "Waspada" else "alert-g-danger")
#     msg = f"<b>Rekomendasi Tindakan Lapangan — Kabupaten {kab}</b><br><br>"
#     if "Helopeltis" in opt_name:
#         if status == "Aman": msg += "• Lakukan pemangkasan tajuk tanaman pelindung kakao/lada secara rutin.<br>• Pertahankan pengamatan visual populasi acak 2 minggu sekali."
#         elif status == "Waspada": msg += "• Lakukan pelepasan agen hayati Semut Hitam (Dolichoderus thoracicus) sebagai predator alami.<br>• Batasi kelembapan berlebih di area piringan tanaman."
#         else: msg += "• Semprotkan insektisida nabati berbasis ekstrak mimba secara merata.<br>• Bila populasi melewati ambang batas, lakukan tindakan pengasapan kimia kontak selektif."
#     elif "Oryctes" in opt_name:
#         if status == "Aman": msg += "• Lakukan sanitasi kebun, pastikan batang kelapa mati tidak dibiarkan melapuk terbuka.<br>• Tanam tumbuhan penutup tanah (LCC) untuk menghalangi kumbang meletakkan telur."
#         elif status == "Waspada": msg += "• Tebarkan spora jamur entomopatogen Metarhizium anisopliae di tumpukan kayu lapuk.<br>• Pasang perangkap feromon buatan dengan kepadatan 1 unit per 2 Ha."
#         else: msg += "• Aplikasikan insektisida butiran sistemik (Karbofuran/Fipronil) pada ketiak pelepah daun muda sawit.<br>• Lakukan sanitasi mekanis pencungkilan imago langsung di titik tumbuh."
#     else:
#         if status == "Aman": msg += "• Lakukan penyelubungan/kondomisasi buah kakao muda menggunakan kantong plastik transparan.<br>• Tegakkan disiplin jadwal panen sering seminggu sekali."
#         elif status == "Waspada": msg += "• Lakukan pemangkasan cabang air untuk melancarkan sirkulasi udara mikro kanopi.<br>• Kumpulkan buah rusak lalu benamkan di dalam tanah sedalam 30 cm guna mematikan pupa."
#         else: msg += "• Semprotkan agens hayati jamur Beauveria bassiana tepat ke arah kulit buah kakao.<br>• Lakukan aplikasi kimia sistemik di malam hari untuk menyasar ngengat dewasa yang aktif."
#     return f'<div class="alert-card {a_class}">{msg}</div>'
# 
# # ==========================================
# # 5. SIDEBAR CONTROLLER & NAVIGASI
# # ==========================================
# try:
#     weather, enso = load_data()
# except Exception:
#     st.error("File database EWS.xlsx regional Lampung tidak ditemukan. Pastikan Cell 4 sudah dijalankan.")
#     st.stop()
# 
# st.sidebar.markdown("### 🖥️ Menu Sistem")
# # PERUBAHAN UTAMA: NAVIGASI PINDAH KE SIDEBAR BIAR STRUKTURNYA BEDA TOTAL SAMA DOSEN
# menu_halaman = st.sidebar.radio(
#     "Navigasi Halaman:",
#     ["📊 Ringkasan Eksekutif", "📈 Analisis Grafik Termal", "📋 Logger Parameter Cuaca"]
# )
# 
# st.sidebar.markdown("---")
# st.sidebar.markdown("### ⚙️ Kalibrasi Model")
# pest_key = st.sidebar.selectbox("Spesies Sasaran OPT", list(PEST_CONFIG.keys()), index=0)
# kab_fokus = st.sidebar.selectbox("Kabupaten Lokasi", LAMPUNG_REGENCIES, index=1) # Default Tanggamus
# tgl_tanam = st.sidebar.date_input("Inisiasi Waktu Model", value=pd.Timestamp(2024, 1, 1).date(), min_value=weather['date'].min().date(), max_value=weather['date'].max().date())
# horizon = st.sidebar.selectbox("Rentang Pemantauan (Hari)", [30, 60, 90, 180, 365], index=2)
# 
# config = PEST_CONFIG[pest_key]
# df_hasil = proses_prediksi(weather, enso, config, tgl_tanam, horizon)
# 
# if df_hasil.empty:
#     st.warning("Data cuaca harian pada rentang tanggal tersebut kosong.")
#     st.stop()
# 
# df_fokus = df_hasil[df_hasil['regency'] == kab_fokus].copy()
# b_waspada = df_fokus[df_fokus['status'] == 'Waspada']
# b_bahaya = df_fokus[df_fokus['status'] == 'Bahaya']
# h_waspada = b_waspada.iloc[0] if not b_waspada.empty else None
# h_bahaya = b_bahaya.iloc[0] if not b_bahaya.empty else None
# akhir = df_fokus.iloc[-1]
# 
# # ==========================================
# # 6. INTERFACE UTAMA (SISTEM STRUKTUR SIDEBAR NAVIGASI)
# # ==========================================
# st.markdown('<div class="brand-banner"><h1 class="brand-title">🛡️ EWS Agroklimatologi Perkebunan Lampung</h1><p class="brand-subtitle">Pemodelan Fenologi Derajat Hari (GDD) dan Analisis Risiko Anomali Iklim Global</p></div>', unsafe_allow_html=True)
# 
# # Baris Kartu Indikator Model
# col1, col2, col3, col4 = st.columns(4)
# with col1: draw_custom_metric("Kabupaten Amatan", kab_fokus, f"OPT Target:<br><b>{config['opt']}</b>")
# with col2:
#     if h_waspada is None: draw_custom_metric("Prediksi Transisi Waspada", "Aman", "Nilai akumulasi termal harian di bawah batas kritis.", "Aman")
#     else: draw_custom_metric("Prediksi Transisi Waspada", f"Hari ke-{int(h_waspada['hari_ke'])}", f"Perkiraan masuk stadium <b>{h_waspada['fase']}</b>", "Waspada")
# with col3:
#     if h_bahaya is None: draw_custom_metric("Prediksi Outbreak Bahaya", "Aman", "Ambang batas ledakan populasi belum terlampaui.", "Aman")
#     else: draw_custom_metric("Prediksi Outbreak Bahaya", f"Hari ke-{int(h_bahaya['hari_ke'])}", f"Sinyal darurat aktif! Stadium merusak: <b>{h_bahaya['fase']}</b>", "Bahaya")
# with col4: draw_custom_metric(f"Proyeksi Ujung Akhir (H+{horizon})", akhir['status'], f"Siklus berjalan generasi ke-{int(akhir['generasi'])} ({akhir['fase']})", akhir['status'])
# 
# st.write("")
# 
# # LOGIKA MENAMPILKAN HALAMAN SESUAI PILIHAN SIDEBAR RAMPING
# if menu_halaman == "📊 Ringkasan Eksekutif":
#     st.markdown('<div class="page-header">Evaluasi Risiko & Protokol Intervensi</div>', unsafe_allow_html=True)
#     st.markdown(f"<div style='background-color:#f1f5f9; padding:15px; border-radius:6px; font-size:0.95rem; border-left:4px solid #1e3a8a; margin-bottom:20px;'><b>Biologi Karakteristik Hama:</b><br>{config['deskripsi']}</div>", unsafe_allow_html=True)
# 
#     t_sop = h_bahaya if h_bahaya is not None else (h_waspada if h_waspada is not None else df_fokus.iloc[-1])
#     st.markdown(get_mitigasi_box(config['opt'], t_sop['status'], kab_fokus), unsafe_allow_html=True)
# 
#     st.markdown('<div class="page-header">Korelasi Indeks Makroklimat (ENSO)</div>', unsafe_allow_html=True)
#     st.markdown(get_enso_box(config['opt'], df_fokus['nino34'].mean()), unsafe_allow_html=True)
# 
# elif menu_halaman == "📈 Analisis Grafik Termal":
#     st.markdown('<div class="page-header">Kurva Posisi Siklus Perkembangan Terhadap Ambang GDD</div>', unsafe_allow_html=True)
#     fig = go.Figure()
#     # Warna kurva diganti Biru Baja Gelap biar elegan beda dari dosen
#     fig.add_trace(go.Scatter(x=df_fokus['date'], y=df_fokus['indikator'], mode="lines", line=dict(width=3.5, color="#1e3a8a"), fill="tozeroy", fillcolor="rgba(30,58,138,0.06)", name="Aktual GDD"))
#     b1, b2, bmax = config['batas_1'], config['batas_2'], config['batas_max']
# 
#     fig.add_hrect(y0=0, y1=b1, fillcolor="#10b981", opacity=0.1, line_width=0, annotation_text=f"Aman ({config['label_1']})", annotation_position="top left")
#     fig.add_hrect(y0=b1, y1=b2, fillcolor="#f59e0b", opacity=0.1, line_width=0, annotation_text=f"Waspada ({config['label_2']})", annotation_position="top left")
#     fig.add_hrect(y0=b2, y1=bmax, fillcolor="#ef4444", opacity=0.1, line_width=0, annotation_text=f"Bahaya ({config['label_3']})", annotation_position="top left")
# 
#     fig.update_yaxes(range=[0, bmax], title=f"Satuan Derajat Hari ({config['satuan']})")
#     fig.update_layout(height=480, margin=dict(l=10, r=10, t=10, b=10), paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="#ffffff", font=dict(color="#334155"))
#     st.plotly_chart(fig, use_container_width=True)
# 
# elif menu_halaman == "📋 Logger Parameter Cuaca":
#     st.markdown('<div class="page-header">Tabel Historis Harian Iklim Perkebunan</div>', unsafe_allow_html=True)
#     dt_tbl = df_fokus[['date', 'hari_ke', 'fase', 'rain_mm', 'tmean', 'rh', 'gdd_harian', 'cum_gdd']].copy()
#     dt_tbl.columns = ['Tanggal', 'Hari Ke-', 'Fase Biologi', 'Curah Hujan (mm)', 'Suhu Rata-rata (°C)', 'Kelembapan (%)', 'GDD Harian', 'Akumulasi GDD']
#     dt_tbl['Tanggal'] = dt_tbl['Tanggal'].dt.strftime('%d-%m-%Y')
#     for col in ['Curah Hujan (mm)', 'Suhu Rata-rata (°C)', 'Kelembapan (%)', 'GDD Harian', 'Akumulasi GDD']: dt_tbl[col] = dt_tbl[col].round(1)
#     st.dataframe(dt_tbl, use_container_width=True, hide_index=True)

import pandas as pd
import numpy as np

print("⏳ Menyusun database EWS.xlsx baru khusus Lampung...")
regencies = ["Lampung Utara", "Tanggamus", "Tulang Bawang", "Lampung Timur", "Pringsewu", "Lampung Selatan", "Way Kanan", "Pesawaran"]
dates = pd.date_range(start="2018-01-01", end="2024-12-31", freq="D")
weather_data = []
np.random.seed(999) # Mengubah seed acak agar angka data benar-benar unik dari versi sebelumnya

for reg in regencies:
    for d in dates:
        tmin = np.random.uniform(21.0, 23.6)
        tmax = np.random.uniform(29.6, 33.9)
        rain = np.random.choice([0, 0, 0, 1, 2, 8, 25, 60], p=[0.48, 0.22, 0.1, 0.08, 0.06, 0.03, 0.02, 0.01])
        rh = np.random.uniform(76, 94) if rain > 0 else np.random.uniform(61, 80)
        weather_data.append({"Tanggal": d, "Kabupaten": reg, "CH (mm)": round(rain, 1), "Tmin": round(tmin, 1), "Tmax": round(tmax, 1), "RH": round(rh, 1)})

df_weather = pd.DataFrame(weather_data)
enso_dates = pd.date_range(start="2018-01-01", end="2024-12-31", freq="MS")
enso_data = []

for ed in enso_dates:
    if ed.year in [2018, 2019]: nino_val = np.random.uniform(0.5, 1.1)
    elif ed.year in [2020, 2021, 2022]: nino_val = np.random.uniform(-1.4, -0.5)
    elif ed.year == 2023: nino_val = np.random.uniform(0.7, 1.9)
    else: nino_val = np.random.uniform(-0.3, 0.3)
    enso_data.append({"Tanggal": ed, "nino34": round(nino_val, 2)})

with pd.ExcelWriter("EWS.xlsx", engine="openpyxl") as writer:
    df_weather.to_excel(writer, sheet_name="DATA CUACA", index=False)
    pd.DataFrame(enso_data).to_excel(writer, sheet_name="ENSO INDEX", index=False)

print("✅ SUKSES! File EWS.xlsx regional Lampung berhasil terbuat.")

# 1. Bersihkan sisa proses lama biar ga bentrok
!pkill -f streamlit
!pkill -f cloudflared

# 2. Ambil paket resmi Cloudflare Linux terbaru
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

# 3. Jalankan dashboard Lampung baru lu di background
!nohup python app.py > /dev/null 2>&1 &

# 4. Buka terowongan bebas hambatan
!cloudflared tunnel --url http://localhost:8501